# Generated by Django 4.2.5 on 2024-03-01 11:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('department', models.CharField(max_length=500)),
                ('Teacher', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='student_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('courses', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
    ]
