# Generated by Django 5.0.2 on 2024-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_rename_teacher_courses_detail_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='department_mod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=256)),
            ],
        ),
    ]
